spring:
  application:
    name: inbox-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <clientid>
              client-secret: <clientsecret>
  data:
    cassandra:
      keyspace-name: main
      username: <clientid>
      password: <clientsecret>
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
datastax:
  astra:
    secure-connect-bundle: secure-connect.zip
astra:
  db:
    id: <dbid>
    region: <region>
    keyspace: <keyspace>
    application:
      token: <token>